name: "🐛 Bug report"
description: Report a bug in the project
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### 🐛 Bug Report
        *Please fill in the following details to help us understand and fix the issue.*

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the unexpected behavior or error.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: List the steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen instead.
      placeholder: Describe the correct behavior or output.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Paste any error messages or add screenshots.
      placeholder: Add logs, stack traces, or screenshots to help explain the problem.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Version or branch, OS, and other relevant setup info.
      placeholder: |
        - Affected version or branch: e.g. `main`, `v0.1`
        - OS: macOS/Linux/Windows
        - Python version / browser / database / etc.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

